#!/usr/bin/env python3
# coding: utf-8
"""CEX per-nucleus vertical kind-manifest renderer (CATALOG bridge W3 / T6).

The CATALOG bridge gives every nucleus a VERTICAL view of the shared 303-kind
taxonomy + the promoted catalog: which kinds it owns and which catalog domains
route to it. This tool renders that view, one doc per nucleus, and the boots
inject it via --append-system-prompt so each booting nucleus self-selects what
it builds without scanning the whole taxonomy.

Two artifacts cooperate (T5 is the contract this renderer (T6) consumes):

  T5  .cex/config/nucleus_kinds.yaml      -- SOURCE OF TRUTH (committed). Maps each
                                             nucleus -> {domain, primary_kinds,
                                             catalog_domains}. Regenerate with --rebuild.
  T6  this tool                           -- reads T5 + the capability_registry
                                             by_nucleus index -> renders
                                             .cex/P09_config/nucleus_kinds_n0X.md (x7).

Derivation (deterministic, reproducible via --rebuild):
  primary_kinds[n]   = sorted kinds in .cex/kinds_meta.json whose `pillar` maps to
                       nucleus n via PILLAR_TO_NUCLEUS. Pillar is the domain-ownership
                       axis; it is a cleaner signal than llm_function (which yields only
                       3 buckets -- n03/n05/n07 -- and mis-routes schema/orchestration
                       kinds, e.g. type_def GOVERN->n05, workflow PRODUCE->n03).
  catalog_domains[n] = sorted by_domain categories routed to n by inverting
                       catalog_promotion_policy.domain_to_nucleus (the routing-only
                       `fallback` key is excluded -- it is a catch-all, not a domain).
  The three pure domain nuclei (n01 intelligence, n02 marketing, n06 commercial) own no
  base infrastructure kinds; their vertical view is the promoted catalog (catalog_domains
  + by_nucleus). n03/n04/n05/n07 own the base kinds by pillar.

CLI:
  python _tools/cex_nucleus_manifest.py            # render the 7 docs (default)
  python _tools/cex_nucleus_manifest.py --check     # verify the 7 docs are current (exit 1 if stale)
  python _tools/cex_nucleus_manifest.py --rebuild    # regenerate nucleus_kinds.yaml from kinds_meta + policy
  python _tools/cex_nucleus_manifest.py --json       # machine-readable summary

Safety: ADDITIVE (never writes kinds_meta or the registry -- it READS them).
Deterministic (sorted, LF newlines) + idempotent (re-render is byte-identical).
Degrade-never (yaml/registry/kinds_meta absent -> minimal stub, never raises).
ASCII-only per .claude/rules/ascii-code-rule.md.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

KINDS_META_PATH = ROOT / ".cex" / "kinds_meta.json"
POLICY_PATH = ROOT / ".cex" / "config" / "catalog_promotion_policy.yaml"
REGISTRY_PATH = ROOT / ".cex" / "config" / "capability_registry.json"
NUCLEUS_KINDS_YAML = ROOT / ".cex" / "config" / "nucleus_kinds.yaml"
OUT_DIR = ROOT / ".cex" / "P09_config"

# The 7 operational nuclei (n00 genesis is the archetype, not a booting nucleus).
NUCLEI = ["n01", "n02", "n03", "n04", "n05", "n06", "n07"]

NUCLEUS_DOMAINS = {
    "n01": "intelligence",
    "n02": "marketing",
    "n03": "engineering",
    "n04": "knowledge",
    "n05": "operations",
    "n06": "commercial",
    "n07": "orchestration",
}

# Pillar -> owning nucleus. The domain-ownership axis for the base 303-kind taxonomy.
# n03 builds (model/prompt/output/schema/architecture); n04 knows (knowledge/memory);
# n05 operates (tools/eval/config/feedback); n07 orchestrates (orchestration).
PILLAR_TO_NUCLEUS = {
    "P01": "n04",  # Knowledge
    "P02": "n03",  # Model
    "P03": "n03",  # Prompt
    "P04": "n05",  # Tools
    "P05": "n03",  # Output
    "P06": "n03",  # Schema
    "P07": "n05",  # Evaluation
    "P08": "n03",  # Architecture
    "P09": "n05",  # Config
    "P10": "n04",  # Memory
    "P11": "n05",  # Feedback
    "P12": "n07",  # Orchestration
}

# domain_to_nucleus keys that are routing rules, not real by_domain categories.
SPECIAL_DOMAIN_KEYS = {"fallback"}

OUT_NAME = "nucleus_kinds_%s.md"  # nucleus_kinds_n03.md

DOC_AUTOGEN_NOTE = (
    "<!-- AUTOGENERATED by _tools/cex_nucleus_manifest.py from "
    ".cex/config/nucleus_kinds.yaml + capability_registry by_nucleus. "
    "Do not hand-edit; run: python _tools/cex_nucleus_manifest.py -->"
)


def _log(msg: str) -> None:
    """Diagnostics to stderr; stdout stays machine-parseable."""
    print("[nucleus_manifest] %s" % msg, file=sys.stderr)


# ---------------------------------------------------------------------------
# Loaders (degrade-never)
# ---------------------------------------------------------------------------

def load_kinds_meta() -> dict[str, Any]:
    """Load .cex/kinds_meta.json. Empty dict on any error (never raises)."""
    try:
        data = json.loads(KINDS_META_PATH.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except Exception as exc:
        _log("kinds_meta unavailable: %s" % exc)
        return {}


def load_domain_map() -> dict[str, str]:
    """Load catalog_promotion_policy.domain_to_nucleus (domain -> nucleus id).

    Excludes SPECIAL_DOMAIN_KEYS. Empty dict on any error (never raises)."""
    try:
        import yaml
    except Exception as exc:
        _log("pyyaml unavailable: %s" % exc)
        return {}
    try:
        doc = yaml.safe_load(POLICY_PATH.read_text(encoding="utf-8")) or {}
    except Exception as exc:
        _log("promotion policy unavailable: %s" % exc)
        return {}
    raw = doc.get("domain_to_nucleus", {}) if isinstance(doc, dict) else {}
    out: dict[str, str] = {}
    if isinstance(raw, dict):
        for domain, nucleus in raw.items():
            if domain in SPECIAL_DOMAIN_KEYS:
                continue
            if isinstance(domain, str) and isinstance(nucleus, str):
                out[domain] = nucleus.strip().lower()
    return out


def load_registry_by_nucleus() -> dict[str, list[str]]:
    """Load capability_registry indexes.by_nucleus (nucleus -> [agent ids]).

    Empty dict on any error (never raises). READ-ONLY -- never writes the registry."""
    try:
        data = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    except Exception as exc:
        _log("capability_registry unavailable: %s" % exc)
        return {}
    idx = data.get("indexes", {}) if isinstance(data, dict) else {}
    byn = idx.get("by_nucleus", {}) if isinstance(idx, dict) else {}
    out: dict[str, list[str]] = {}
    if isinstance(byn, dict):
        for nucleus, items in byn.items():
            if isinstance(items, list):
                out[str(nucleus)] = [str(i) for i in items]
    return out


# ---------------------------------------------------------------------------
# Derivation
# ---------------------------------------------------------------------------

def derive_nucleus_kinds(
    kinds_meta: dict[str, Any] | None = None,
    domain_map: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Derive the per-nucleus manifest from kinds_meta (pillar) + the domain map.

    Pure + deterministic: same inputs -> identical output (all lists sorted).
    Returns {"version": "1.0", "nuclei": {n0X: {domain, primary_kinds, catalog_domains}}}.
    """
    if kinds_meta is None:
        kinds_meta = load_kinds_meta()
    if domain_map is None:
        domain_map = load_domain_map()

    primary: dict[str, list[str]] = {n: [] for n in NUCLEI}
    for kind, meta in kinds_meta.items():
        pillar = (meta or {}).get("pillar", "") if isinstance(meta, dict) else ""
        owner = PILLAR_TO_NUCLEUS.get(pillar)
        if owner in primary:
            primary[owner].append(str(kind))

    catalog: dict[str, list[str]] = {n: [] for n in NUCLEI}
    for domain, nucleus in domain_map.items():
        if domain in SPECIAL_DOMAIN_KEYS:
            continue  # routing catch-all, not a real by_domain category
        if nucleus in catalog:
            catalog[nucleus].append(domain)

    nuclei: dict[str, Any] = {}
    for n in NUCLEI:
        nuclei[n] = {
            "domain": NUCLEUS_DOMAINS[n],
            "primary_kinds": sorted(primary[n]),
            "catalog_domains": sorted(catalog[n]),
        }
    return {"version": "1.0", "nuclei": nuclei}


def _normalize_manifest(raw: Any) -> dict[str, Any]:
    """Coerce a loaded manifest into a well-formed shape with all 7 nuclei present.

    Missing / malformed nuclei get a stub entry so render never crashes."""
    nuclei_in = {}
    if isinstance(raw, dict):
        candidate = raw.get("nuclei")
        if isinstance(candidate, dict):
            nuclei_in = candidate
    nuclei: dict[str, Any] = {}
    for n in NUCLEI:
        entry = nuclei_in.get(n) if isinstance(nuclei_in.get(n), dict) else {}
        domain = entry.get("domain")
        if not isinstance(domain, str) or not domain:
            domain = NUCLEUS_DOMAINS[n]
        prim = entry.get("primary_kinds")
        prim = sorted(str(k) for k in prim) if isinstance(prim, list) else []
        cat = entry.get("catalog_domains")
        cat = sorted(str(d) for d in cat) if isinstance(cat, list) else []
        nuclei[n] = {"domain": domain, "primary_kinds": prim, "catalog_domains": cat}
    version = raw.get("version") if isinstance(raw, dict) else None
    return {"version": version if isinstance(version, str) else "1.0", "nuclei": nuclei}


def load_manifest() -> dict[str, Any]:
    """Load the manifest: committed yaml (source of truth) -> derive -> stub.

    1. .cex/config/nucleus_kinds.yaml present + parseable -> use it (normalized).
    2. else derive from kinds_meta + policy (when those are available).
    3. else a minimal stub (all 7 nuclei, empty lists). Never raises.
    """
    if NUCLEUS_KINDS_YAML.is_file():
        try:
            import yaml
            raw = yaml.safe_load(NUCLEUS_KINDS_YAML.read_text(encoding="utf-8"))
            return _normalize_manifest(raw)
        except Exception as exc:
            _log("nucleus_kinds.yaml unreadable, falling back to derive: %s" % exc)
    # No committed yaml -> derive (or stub when inputs are absent).
    return _normalize_manifest(derive_nucleus_kinds())


# ---------------------------------------------------------------------------
# YAML emit (deterministic, pyyaml-version-independent, ASCII)
# ---------------------------------------------------------------------------

def _yaml_header() -> list[str]:
    return [
        "# .cex/config/nucleus_kinds.yaml -- per-nucleus vertical kind-manifest "
        "(CATALOG bridge W3 / T5).",
        "# SOURCE OF TRUTH for the boot view. cex_nucleus_manifest.py reads this + the",
        "# capability_registry by_nucleus index to render "
        ".cex/P09_config/nucleus_kinds_n0X.md (x7).",
        "#",
        "# DO NOT hand-edit. Regenerate when kinds_meta.json or the promotion policy "
        "changes:",
        "#   python _tools/cex_nucleus_manifest.py --rebuild",
        "#",
        "# DERIVATION (deterministic):",
        "#   primary_kinds[n]   = sorted kinds whose kinds_meta pillar maps to n via",
        "#                        PILLAR_TO_NUCLEUS (P01->n04 P02->n03 P03->n03 P04->n05",
        "#                        P05->n03 P06->n03 P07->n05 P08->n03 P09->n05 P10->n04",
        "#                        P11->n05 P12->n07). Pillar is the domain-ownership axis.",
        "#   catalog_domains[n] = sorted by_domain categories routed to n by inverting",
        "#                        catalog_promotion_policy.domain_to_nucleus (the routing",
        "#                        catch-all `fallback` key is excluded).",
        "#   n01/n02/n06 are domain verticals: no base kinds, served by catalog_domains.",
    ]


def dump_yaml(manifest: dict[str, Any]) -> str:
    """Render the manifest to a deterministic, ASCII, block-style YAML string.

    Hand-formatted (not yaml.safe_dump) so output is byte-stable across pyyaml
    versions. Round-trips through yaml.safe_load."""
    manifest = _normalize_manifest(manifest)
    lines: list[str] = list(_yaml_header())
    lines.append('version: "%s"' % manifest["version"])
    lines.append("nuclei:")
    for n in NUCLEI:
        entry = manifest["nuclei"][n]
        lines.append("  %s:" % n)
        lines.append("    domain: %s" % entry["domain"])
        prim = entry["primary_kinds"]
        if prim:
            lines.append("    primary_kinds:")
            for kind in prim:
                lines.append("    - %s" % kind)
        else:
            lines.append("    primary_kinds: []")
        cat = entry["catalog_domains"]
        if cat:
            lines.append("    catalog_domains:")
            for domain in cat:
                lines.append("    - %s" % domain)
        else:
            lines.append("    catalog_domains: []")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Doc render (deterministic, ASCII)
# ---------------------------------------------------------------------------

def _bullet_section(title: str, items: list[str], empty_note: str) -> list[str]:
    lines = ["## %s (%d)" % (title, len(items))]
    if items:
        for item in items:
            lines.append("- %s" % item)
    else:
        lines.append(empty_note)
    lines.append("")
    return lines


def render_doc(nucleus: str, entry: dict[str, Any], registry_items: list[str]) -> str:
    """Render one nucleus_kinds_n0X.md doc. Deterministic + ASCII."""
    domain = entry.get("domain", NUCLEUS_DOMAINS.get(nucleus, "?"))
    primary = sorted(entry.get("primary_kinds", []) or [])
    catalog = sorted(entry.get("catalog_domains", []) or [])
    registry = sorted(registry_items or [])
    upper = nucleus.upper()

    lines: list[str] = [
        "# %s vertical kind-manifest -- %s" % (upper, domain),
        DOC_AUTOGEN_NOTE,
        "",
        "%s (%s) vertical view of the CEX taxonomy. Injected at boot via "
        "--append-system-prompt." % (upper, domain),
        "These are the kinds and catalog domains this nucleus owns; the rest of the "
        "303-kind taxonomy belongs to other nuclei. Use it to self-select what you build.",
        "",
    ]
    lines += _bullet_section(
        "Primary kinds", primary,
        "(none -- this nucleus is a domain vertical; its capabilities come from the "
        "promoted catalog below)")
    lines += _bullet_section(
        "Catalog domains", catalog,
        "(none routed to this nucleus)")
    lines += _bullet_section(
        "Registry capabilities (by_nucleus)", registry,
        "(none yet -- promoted catalog items appear here after the catalog sync)")
    # Trim trailing blank line to a single terminal newline.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def render_all(
    manifest: dict[str, Any] | None = None,
    by_nucleus: dict[str, list[str]] | None = None,
) -> dict[str, str]:
    """Render all 7 docs. Returns {absolute_path_str: content}. Deterministic."""
    manifest = _normalize_manifest(manifest) if manifest is not None else load_manifest()
    if by_nucleus is None:
        by_nucleus = load_registry_by_nucleus()
    out: dict[str, str] = {}
    for n in NUCLEI:
        entry = manifest["nuclei"][n]
        content = render_doc(n, entry, by_nucleus.get(n, []))
        out[str(OUT_DIR / (OUT_NAME % n))] = content
    return out


# ---------------------------------------------------------------------------
# IO helpers (LF newlines -> byte-stable cross-platform)
# ---------------------------------------------------------------------------

def _write_lf(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def _matches_disk(path: Path, content: str) -> bool:
    """Newline-tolerant content compare. The renderer always writes LF, but git
    autocrlf may check the committed doc out as CRLF on Windows -- read_text applies
    universal-newline translation so a CRLF working copy still verifies as current.
    Keeps --check correct cross-platform (zero-drift multi-user)."""
    try:
        return path.read_text(encoding="utf-8") == content
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_render() -> dict[str, Any]:
    docs = render_all()
    written = []
    for path_str, content in sorted(docs.items()):
        _write_lf(Path(path_str), content)
        written.append(Path(path_str).name)
    return {"action": "render", "written": written, "count": len(written)}


def cmd_check() -> dict[str, Any]:
    docs = render_all()
    stale: list[str] = []
    missing: list[str] = []
    for path_str, content in sorted(docs.items()):
        path = Path(path_str)
        if not path.is_file():
            missing.append(path.name)
        elif not _matches_disk(path, content):
            stale.append(path.name)
    ok = not stale and not missing
    return {"action": "check", "ok": ok, "stale": stale, "missing": missing,
            "count": len(docs)}


def cmd_rebuild() -> dict[str, Any]:
    manifest = derive_nucleus_kinds()
    content = dump_yaml(manifest)
    _write_lf(NUCLEUS_KINDS_YAML, content)
    counts = {n: len(manifest["nuclei"][n]["primary_kinds"]) for n in NUCLEI}
    return {"action": "rebuild", "path": str(NUCLEUS_KINDS_YAML.relative_to(ROOT)),
            "primary_kind_counts": counts}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render per-nucleus vertical kind-manifest docs (CATALOG W3 / T6).")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true",
                       help="Verify the 7 docs are current (exit 1 if any stale/missing).")
    group.add_argument("--rebuild", action="store_true",
                       help="Regenerate .cex/config/nucleus_kinds.yaml from kinds_meta + policy.")
    parser.add_argument("--json", action="store_true", help="Emit the result as JSON.")
    args = parser.parse_args(argv)

    if args.rebuild:
        result = cmd_rebuild()
    elif args.check:
        result = cmd_check()
    else:
        result = cmd_render()

    if args.json:
        print(json.dumps(result, ensure_ascii=True, indent=2))
    else:
        action = result.get("action")
        if action == "check":
            if result["ok"]:
                print("[nucleus_manifest] OK: %d docs current" % result["count"])
            else:
                if result["missing"]:
                    print("[nucleus_manifest] MISSING: %s" % ", ".join(result["missing"]))
                if result["stale"]:
                    print("[nucleus_manifest] STALE: %s" % ", ".join(result["stale"]))
                print("[nucleus_manifest] run: python _tools/cex_nucleus_manifest.py")
        elif action == "rebuild":
            print("[nucleus_manifest] rebuilt %s" % result["path"])
            for n in NUCLEI:
                print("  %s primary_kinds: %d" % (n, result["primary_kind_counts"][n]))
        else:
            print("[nucleus_manifest] rendered %d docs: %s" % (
                result["count"], ", ".join(result["written"])))

    if result.get("action") == "check" and not result.get("ok"):
        return 1
    return 0


if __name__ == "__main__":
    try:
        from cex_agent_io import wrap_main

        def _main_wrapper(argv: list[str]) -> int:
            return main(argv)

        sys.exit(wrap_main(_main_wrapper, sys.argv[1:], label="cex_nucleus_manifest"))
    except ImportError:
        sys.exit(main())
