#!/usr/bin/env python3
# -*- coding: ascii -*-
"""CEXAI media-persist -- apply a human upload to a persisted dual-output asset (PURE logic).

THE STEP between the store (cex_media_store: bytes -> src) and the DB (cex_runtime_sync:
read/update the tenant_data row). Given the CURRENTLY-persisted dual_output ({id, machine_md,
media_slots}) + the run's structured payload + a target slot_key + the new ``src``, produce the
UPDATED dual_output with that slot flipped empty -> generated and BOTH faces kept consistent.

HOW (reuse, never re-implement): it reconstructs the ``media_requests`` (one per current slot,
preserving key/kind/section/label) and ``produced_media`` (every already-generated slot's src,
PLUS the uploaded slot's new src), then re-runs the CANONICAL emitter ``cex_dual_output
.to_dual_output``. So the new machine .md, the media ledger, and the human face are regenerated by
the SAME pure projection the run used -- they can never drift. The asset ``id`` is preserved (the
coupling is stable across the edit).

LEAN MACHINE FACE: a base64 ``data:`` URI (the V1 inline sink) is huge; inlining it into the
machine .md would bloat the AI-readable face. So the regenerated .md has its base64 data URIs
ELIDED to a short marker (the real src still rides ``media_slots[key].src`` -- the structured
field the AI reads for the actual bytes). Non-base64 srcs (e.g. the url-encoded SVG samples, real
CDN/object-store URLs) are LEFT INTACT.

PURE + TOTAL: no IO, no DB, no network. A missing slot_key -> MediaPersistError('unknown_slot',
404); an empty src -> MediaPersistError('empty_src', 400). ASCII-only per
.claude/rules/ascii-code-rule.md.

Consumer: apps/dashboard_api/main.py (PATCH /capability/{record_id}/media/{slot_key}). Sibling:
cex_media_store (the sink), cex_dual_output (the emitter), cex_runtime_sync (the DB read/update).
"""

from __future__ import annotations

import re
from typing import Any, Dict, List, Mapping, Optional


class MediaPersistError(Exception):
    """A media-persist failure mapped to a precise HTTP status (never a secret/traceback)."""

    def __init__(self, reason: str, *, status: int = 400, detail: str = "") -> None:
        self.reason = reason
        self.status = status
        self.detail = detail or reason
        super().__init__(self.detail)


# A base64 data URI (the inline-sink src). Non-base64 data URIs (e.g. ``data:image/svg+xml,...``)
# do NOT match -- they are left intact (they are small + meaningful in the .md).
_DATA_URI_B64 = re.compile(r"data:([\w.+\-]+/[\w.+\-]+)?;base64,[A-Za-z0-9+/=]+")


def _elide_data_uris(md: str) -> str:
    """Replace each base64 ``data:`` URI in the machine .md with a short marker (the real bytes
    stay in media_slots[key].src). Keeps the AI-readable face lean. TOTAL."""
    if not md:
        return md

    def _repl(m: "re.Match[str]") -> str:
        mime = m.group(1) or "application/octet-stream"
        full = m.group(0)
        marker = "base64,"
        b64_len = len(full) - (full.index(marker) + len(marker))
        return "data:%s;base64,[%d chars omitted -- persisted upload]" % (mime, b64_len)

    return _DATA_URI_B64.sub(_repl, md)


def _slot_request(slot: Mapping[str, Any]) -> Optional[Dict[str, Any]]:
    """Reconstruct a media_request {key, kind, section?, label?} from a persisted slot. None when
    the slot has no usable key/kind (it is dropped -- never fabricated)."""
    key = str(slot.get("key") or "").strip()
    kind = str(slot.get("kind") or "").strip().lower()
    if not key or not kind:
        return None
    req: Dict[str, Any] = {"key": key, "kind": kind}
    section = slot.get("section")
    if isinstance(section, str) and section.strip():
        req["section"] = section.strip()
    label = slot.get("label")
    if isinstance(label, str) and label.strip():
        req["label"] = label.strip()
    return req


def _load_emitter() -> Any:
    """Import cex_dual_output.to_dual_output (same _tools dir). Guarded so a degraded env raises a
    clean MediaPersistError rather than an ImportError at request time."""
    try:
        from cex_dual_output import to_dual_output  # type: ignore
    except Exception:  # pragma: no cover - environment guard
        try:
            import sys
            from pathlib import Path

            tools = str(Path(__file__).resolve().parent)
            if tools not in sys.path:
                sys.path.insert(0, tools)
            from cex_dual_output import to_dual_output  # type: ignore
        except Exception as exc:  # pragma: no cover
            raise MediaPersistError(
                "emitter_unavailable", status=500,
                detail="dual-output emitter not importable: %s" % exc,
            )
    return to_dual_output


def apply_upload_to_dual_output(
    dual_output: Mapping[str, Any],
    structured: Optional[Mapping[str, Any]],
    capability: str,
    slot_key: str,
    src: str,
    *,
    tenant: Optional[str] = None,
    created: Optional[str] = None,
) -> Dict[str, Any]:
    """Return the UPDATED persisted dual_output ({id, capability, machine_md, media_slots, real})
    with ``slot_key`` flipped to generated (src filled) and both faces regenerated consistently.

    FAIL-CLOSED: an unknown slot_key -> 404; an empty src -> 400. PURE + TOTAL otherwise.
    """
    if not isinstance(dual_output, Mapping):
        raise MediaPersistError("no_dual_output", status=404, detail="no dual_output to update")
    new_src = (src or "").strip()
    if not new_src:
        raise MediaPersistError("empty_src", status=400, detail="the stored src is empty")

    raw_slots = dual_output.get("media_slots")
    slots: List[Mapping[str, Any]] = [s for s in raw_slots if isinstance(s, Mapping)] \
        if isinstance(raw_slots, (list, tuple)) else []
    if not slots:
        raise MediaPersistError("no_media_slots", status=404,
                                detail="this asset declares no media slots")

    target_key = (slot_key or "").strip()
    if not any(str(s.get("key") or "").strip() == target_key for s in slots):
        raise MediaPersistError("unknown_slot", status=404,
                                detail="no media slot %r on this asset" % target_key)

    # Reconstruct the requests (one per slot, order-preserving) + the produced map (every
    # already-generated slot's src, PLUS the uploaded slot's new src -- the upload wins).
    requests: List[Dict[str, Any]] = []
    produced: Dict[str, Any] = {}
    for s in slots:
        req = _slot_request(s)
        if req is None:
            continue
        requests.append(req)
        existing = s.get("src")
        if (str(s.get("status") or "") == "generated" and isinstance(existing, str)
                and existing.strip()):
            produced[req["key"]] = existing.strip()
    produced[target_key] = new_src  # the upload fills (or replaces) the target slot

    cap = (capability or str(dual_output.get("capability") or "") or "capability").strip()
    asset_id = dual_output.get("id")
    struct = structured if isinstance(structured, Mapping) else {}

    to_dual_output = _load_emitter()
    regenerated = to_dual_output(
        cap, struct,
        media_requests=requests,
        produced_media=produced,
        asset_id=str(asset_id) if asset_id else None,
        tenant=tenant,
        created=created,
    )

    return {
        "id": regenerated.get("id"),
        "capability": regenerated.get("capability"),
        "machine_md": _elide_data_uris(str(regenerated.get("machine_md") or "")),
        "media_slots": regenerated.get("media_slots"),
        "real": regenerated.get("real"),
    }


__all__ = ["apply_upload_to_dual_output", "MediaPersistError"]
