# CEX N01 -- CEX-N01-RESEARCH (GEMINI)
# Generated by cex_boot_gen.py -- CLI override: gemini
# Model: gemini-2.5-flash | Handoff suffix: _gemini

. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI
. $PSScriptRoot/_shared/emit_exit_signal.ps1
. $PSScriptRoot/_shared/fix_pathext.ps1  # Guard: .PS1 before .CMD breaks npx-based MCP servers
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n01"
. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme

# Detect mission from handoff file. TENANT-SCOPED (R-042): 'runtime' is a
# per-tenant surface, so a tenant session reads/writes its OWN handoff
# (.cex/tenants/<tid>/runtime/handoffs/), never the global/central one --
# stops a tenant nucleus from colliding with the central (or another
# tenant's) handoff when both run on the same machine.
$mission = ""
$handoffRel = if ($env:CEX_TENANT_ID) { ".cex/tenants/$($env:CEX_TENANT_ID)/runtime/handoffs/${nucleus}_task_gemini.md" } else { ".cex/runtime/handoffs/${nucleus}_task_gemini.md" }
$handoff = Join-Path $cexRoot ($handoffRel -replace '/', '\')
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

function Set-CexTitle($status) {
    # window-title mechanic intentionally omitted (de-branded distribution build)
}

Set-CexTitle "BOOTING"

try {
    $Host.UI.RawUI.BackgroundColor = "DarkBlue"
    $Host.UI.RawUI.ForegroundColor = "White"
    if (-not $env:CEX_GRID) {
        $bufSize = $Host.UI.RawUI.BufferSize
        $bufSize.Width = 160; $bufSize.Height = 9999
        $Host.UI.RawUI.BufferSize = $bufSize
        $winSize = $Host.UI.RawUI.WindowSize
        $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
        $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
        $Host.UI.RawUI.WindowSize = $winSize
    }
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N01 RESEARCH via GEMINI" -ForegroundColor Cyan
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  gemini-2.5-flash  |  8F pipeline  |  handoff: ${nucleus}_task_gemini.md" -ForegroundColor DarkGray
if ($mission) { Write-Host "  Mission: $mission" -ForegroundColor Cyan }
Write-Host ""

$env:CEX_NUCLEUS = "N01"
$env:CEX_ROOT = $cexRoot
$env:CEX_CLI = "gemini"
Set-Location $env:CEX_ROOT

# Load .env (secrets for MCP servers, LLM providers). System env wins.
. "$PSScriptRoot\_shared\load_dotenv.ps1"
. "$PSScriptRoot\_shared\check_mcp_env.ps1"  # Pre-flight: warn if MCP env vars are missing

# System context baked into prompt (no --append-system-prompt on gemini)
$sysPrompt = @'
You are N01 Research Nucleus of CEX. Domain: research, analysis, papers, competitors.

You are running via GEMINI CLI in CEX multi-CLI test mode.
Your handoff task is embedded verbatim below (between HANDOFF BEGIN/END) --
do not try to locate or re-read a handoff file yourself; use the embedded
content directly (R-042: the path is tenant-scoped and resolved by the
launcher, not a fixed location you can re-derive).
Read GEMINI.md (Gemini runtime entry) for system-wide configuration.
Rules loaded from:
  - .claude/rules/n07-orchestrator.md
  - N01_intelligence/rules/n01-intelligence.md
  - .claude/rules/8f-reasoning.md
  - .claude/rules/ascii-code-rule.md
Your agent card: N01_intelligence/agent_card_n01.md
Follow 8F pipeline F1->F8. Save output, compile, commit, signal on complete.
'@

# Read handoff inline (bypasses CLI gitignore policy -- gemini respects .gitignore,
# codex does not; this path works for both). TENANT-SCOPED (R-042): reuse the
# $handoff path resolved above (same tenant base as the mission-detection read)
# so a tenant session's actual task body comes from its own handoff, not the
# central one.
$handoffPath = $handoff
if (-not (Test-Path $handoffPath)) {
    # WS5.0 fallback: the claude solo path writes the unsuffixed handoff.
    $handoffRel = if ($env:CEX_TENANT_ID) { ".cex/tenants/$($env:CEX_TENANT_ID)/runtime/handoffs/${nucleus}_task.md" } else { ".cex/runtime/handoffs/${nucleus}_task.md" }
    $handoffPath = Join-Path $cexRoot ($handoffRel -replace '/', '\')
}
if (Test-Path $handoffPath) {
    $handoffBody = Get-Content -Raw -LiteralPath $handoffPath
} else {
    $handoffBody = "(no handoff at $handoffPath -- report ready and exit)"
}

$initialMsg = @"
Execute the task described in the handoff BELOW (embedded verbatim -- do NOT try to re-read the path).
Follow its frontmatter (mission, kind, output path) exactly.
Follow the 8F pipeline. Signal on complete.

=== HANDOFF BEGIN ===
$handoffBody
=== HANDOFF END ===

SYSTEM CONTEXT:
$sysPrompt
"@

$model = if ($env:CEX_MODEL_OVERRIDE) { $env:CEX_MODEL_OVERRIDE } else { "gemini-2.5-flash" }
$cliArgs = @("--approval-mode", "yolo", "--skip-trust", "--model", $model)
$cliArgs += "--include-directories", $cexRoot, "--allowed-mcp-server-names", "none"

# WS5.0 fix (lr_runtime_failure_n04_gemini_boot_20260609): pipe the (large) handoff
# prompt via STDIN; pass only a SHORT directive inline via -p (gemini appends -p to
# stdin). Passing the whole body inline overflowed the Windows command line
# ("Linha de comando muito longa"). Resolve-CliBinary picks the .cmd shim (robust
# under the Start-Process spawn chain where bare "& gemini" can drop the npm shim).
$goDirective = "Execute the task from the standard-input handoff above. Follow the 8F pipeline F1-F8. Use your Write tool to save outputs; commit and signal on complete. Do not enter Plan Mode; do not ask for clarification."

Set-CexTitle "RUNNING"
$cex_start_time = Get-Date
. "$PSScriptRoot\_shared\resolve_cli.ps1"
$geminiBin = Resolve-CliBinary "gemini"
if (-not $geminiBin) {
    Write-Host "[$($nucleus.ToUpper())][FAIL] gemini CLI not found on PATH or npm shim locations" -ForegroundColor Red
    Set-CexTitle "FAIL"
    exit 2
}
$initialMsg | & $geminiBin @cliArgs -p $goDirective
Set-CexTitle "DONE"

exit 0  # auto-close window after task complete (was lingering with -NoExit)
Emit-ExitSignal -StartTime $cex_start_time
