# CEX N04 -- CEX-N04-KNOWLEDGE (CODEX)
# Generated by cex_boot_gen.py -- CLI override: codex
# Model: default | Handoff suffix: _codex

. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI
. $PSScriptRoot/_shared/fix_pathext.ps1  # Guard: .PS1 before .CMD breaks npx-based MCP servers
. $PSScriptRoot/_shared/emit_exit_signal.ps1
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n04"
. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme

# Detect mission from handoff file. TENANT-SCOPED (R-042): 'runtime' is a
# per-tenant surface, so a tenant session reads/writes its OWN handoff
# (.cex/tenants/<tid>/runtime/handoffs/), never the global/central one --
# stops a tenant nucleus from colliding with the central (or another
# tenant's) handoff when both run on the same machine.
$mission = ""
$handoffRel = if ($env:CEX_TENANT_ID) { ".cex/tenants/$($env:CEX_TENANT_ID)/runtime/handoffs/${nucleus}_task_codex.md" } else { ".cex/runtime/handoffs/${nucleus}_task_codex.md" }
$handoff = Join-Path $cexRoot ($handoffRel -replace '/', '\')
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

function Set-CexTitle($status) {
    # window-title mechanic intentionally omitted (de-branded distribution build)
}

Set-CexTitle "BOOTING"

try {
    $Host.UI.RawUI.BackgroundColor = "DarkCyan"
    $Host.UI.RawUI.ForegroundColor = "White"
    if (-not $env:CEX_GRID) {
        $bufSize = $Host.UI.RawUI.BufferSize
        $bufSize.Width = 160; $bufSize.Height = 9999
        $Host.UI.RawUI.BufferSize = $bufSize
        $winSize = $Host.UI.RawUI.WindowSize
        $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
        $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
        $Host.UI.RawUI.WindowSize = $winSize
    }
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N04 KNOWLEDGE via CODEX" -ForegroundColor Yellow
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  default  |  8F pipeline  |  handoff: ${nucleus}_task_codex.md" -ForegroundColor DarkGray
if ($mission) { Write-Host "  Mission: $mission" -ForegroundColor Yellow }
Write-Host ""

$env:CEX_NUCLEUS = "N04"
$env:CEX_ROOT = $cexRoot
$env:CEX_CLI = "codex"
Set-Location $env:CEX_ROOT

# Load .env (secrets for MCP servers, LLM providers). System env wins.
. "$PSScriptRoot\_shared\load_dotenv.ps1"
. "$PSScriptRoot\_shared\check_mcp_env.ps1"  # Pre-flight: warn if MCP env vars are missing

# System context baked into prompt (no --append-system-prompt on codex)
$sysPrompt = @'
You are N04 Knowledge Nucleus of CEX. Domain: RAG, indexing, knowledge cards, taxonomy.

You are running via CODEX CLI in CEX multi-CLI test mode.
Your handoff task is embedded verbatim below (between HANDOFF BEGIN/END) --
do not try to locate or re-read a handoff file yourself; use the embedded
content directly (R-042: the path is tenant-scoped and resolved by the
launcher, not a fixed location you can re-derive).
Read AGENTS.md (Codex runtime entry) for system-wide configuration.
Rules loaded from:
  - .claude/rules/n07-orchestrator.md
  - N04_knowledge/rules/n04-knowledge.md
  - .claude/rules/8f-reasoning.md
  - .claude/rules/ascii-code-rule.md
Your agent card: N04_knowledge/P08_architecture/agent_card_n04.md
Follow 8F pipeline F1->F8. Save output, compile, commit, signal on complete.
'@

# Read handoff inline (bypasses CLI gitignore policy -- gemini respects .gitignore,
# codex does not; this path works for both). TENANT-SCOPED (R-042): reuse the
# $handoff path resolved above so a tenant session's actual task body comes
# from its own handoff, not the central one.
$handoffPath = $handoff
if (Test-Path $handoffPath) {
    $handoffBody = Get-Content -Raw -LiteralPath $handoffPath
} else {
    $handoffBody = "(no handoff at $handoffPath -- report ready and exit)"
}

$initialMsg = @"
Execute the task described in the handoff BELOW (embedded verbatim -- do NOT try to re-read the path).
Follow its frontmatter (mission, kind, output path) exactly.
Follow the 8F pipeline. Signal on complete.

=== HANDOFF BEGIN ===
$handoffBody
=== HANDOFF END ===

SYSTEM CONTEXT:
$sysPrompt
"@

$cliArgs = @("--dangerously-bypass-approvals-and-sandbox", "-c", "model_reasoning_effort=high")
$cliArgs += "-C", $cexRoot

Set-CexTitle "RUNNING"
$cex_start_time = Get-Date
$initialMsg | & codex exec @cliArgs -
$exitStatus = if ($LASTEXITCODE -eq 0) { "complete" } else { "exited" }

# Post-exit: auto-commit any uncommitted artifacts (codex exits without committing)
Write-Host ""
Write-Host "  [>>] Post-exit: checking for uncommitted artifacts..." -ForegroundColor DarkGray
git add _showoff/ -A 2>$null
git diff --cached --quiet 2>$null
if (-not $?) {
    git commit -m "[N04] SHOWOFF via codex"
    Write-Host "  [OK] Committed showoff artifacts" -ForegroundColor Green
}

# Post-exit: emit completion signal (codex exits without signalling)
try {
    python -c "import sys; sys.path.insert(0, '_tools'); from signal_writer import write_signal; write_signal('n04', 'complete', 9.0, mission='$mission')"
    Write-Host "  [OK] Signal emitted for n04" -ForegroundColor Green
} catch {
    Write-Host "  [WARN] Signal emission failed: $_" -ForegroundColor Yellow
}

Set-CexTitle "DONE"
Emit-ExitSignal -StartTime $cex_start_time -Status $exitStatus
