# CEX N07 -- CEX-N07-ORCHESTRATOR (CODEX)
# Generated by cex_boot_gen.py -- CLI override: codex
# Model: ChatGPT account default (was gpt-5-codex, not supported on ChatGPT auth) | Handoff suffix: _codex

. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI (claude/gemini/codex/ollama)
. $PSScriptRoot/_shared/fix_pathext.ps1  # Guard: .PS1 before .CMD breaks npx-based MCP servers
. $PSScriptRoot/_shared/emit_exit_signal.ps1
. $PSScriptRoot/_shared/run_with_timeout.ps1
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n07"

. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme (bg color, scrollback)
# Detect mission from handoff file. TENANT-SCOPED (R-042): 'runtime' is a
# per-tenant surface, so a tenant session reads/writes its OWN handoff
# (.cex/tenants/<tid>/runtime/handoffs/), never the global/central one --
# stops a tenant nucleus from colliding with the central (or another
# tenant's) handoff when both run on the same machine.
$mission = ""
$handoffRel = if ($env:CEX_TENANT_ID) { ".cex/tenants/$($env:CEX_TENANT_ID)/runtime/handoffs/${nucleus}_task_codex.md" } else { ".cex/runtime/handoffs/${nucleus}_task_codex.md" }
$handoff = Join-Path $cexRoot ($handoffRel -replace '/', '\')
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

function Set-CexTitle($status) {
    # window-title mechanic intentionally omitted (de-branded distribution build)
}

Set-CexTitle "BOOTING"

$env:CEX_NUCLEUS = "N07"
$env:CEX_ROOT = $cexRoot
$env:CEX_CLI = "codex"
Set-Location $env:CEX_ROOT
. "$PSScriptRoot\_shared\load_dotenv.ps1"
. "$PSScriptRoot\_shared\check_mcp_env.ps1"  # Pre-flight: warn if MCP env vars are missing

# System context baked into prompt (no --append-system-prompt on codex)
$sysPrompt = @"
You are N07 Orchestrator Nucleus of CEX. Domain: dispatch, wave planning, consolidation. IF $handoffRel EXISTS, READ AND EXECUTE IMMEDIATELY.

You are running via CODEX CLI in CEX multi-CLI test mode.
Read the handoff at $handoffRel and execute. (R-042: this path is tenant-scoped
and resolved above -- do not assume the central/default location.)
Read AGENTS.md (Codex runtime entry) for system-wide configuration.
Rules loaded from:
  - .claude/rules/n07-orchestrator.md
  - .claude/rules/n07-*.md
  - .claude/rules/8f-reasoning.md
  - .claude/rules/ascii-code-rule.md
Your agent card: N07_admin/agent_card_n07.md
Follow 8F pipeline F1->F8. Save output, compile, commit, signal on complete.
"@

$initialMsg = @"
Read $handoffRel and execute the task specified in the frontmatter.
Produce the report at the path specified in the handoff frontmatter.
Follow the 8F pipeline. Signal on complete.

SYSTEM CONTEXT:
$sysPrompt
"@

$cliArgs = @("--dangerously-bypass-approvals-and-sandbox", "-c", "model_reasoning_effort=high")
$cliArgs += "-C", $cexRoot

Set-CexTitle "RUNNING"
# [CEX_TUI_HYGIENE] UTF-8 + buffer sync + color reset (prevents TUI bleed/mojibake)
try {
    # 1. UTF-8 codepage + encoding (Claude/Codex/Gemini emit unicode box-drawing)
    $null = (chcp 65001 2>$null)
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    [Console]::InputEncoding = [System.Text.Encoding]::UTF8
    $env:PYTHONIOENCODING = "utf-8"
    # 2. Sync BufferSize.Width to WindowSize.Width (no horizontal scroll, no clip)
    $win = $Host.UI.RawUI.WindowSize
    $buf = $Host.UI.RawUI.BufferSize
    if ($buf.Width -ne $win.Width) {
        $buf.Width = $win.Width
        $buf.Height = [Math]::Max($win.Height, $cexScrollback)
        $Host.UI.RawUI.BufferSize = $buf
    }
    Clear-Host
} catch {}
$cex_start_time = Get-Date
$watchdog = Start-CexWatchdog
$initialMsg | & codex exec @cliArgs -
$exitStatus = Stop-CexWatchdog $watchdog
Set-CexTitle "DONE"
Emit-ExitSignal -StartTime $cex_start_time -Status $exitStatus
