# boot/_shared/resolve_model.ps1
# Resolves CLI model + flags for a nucleus from nucleus_models.yaml at RUNTIME.
# Never hardcode models in boot scripts -- this file is the single resolver.
#
# Usage (from a boot script):
#     . "$PSScriptRoot\_shared\resolve_model.ps1"
#     $resolved = Resolve-NucleusModel -Nucleus "n03" -CexRoot $cexRoot
#     $resolved.model    # "claude-opus-4-8"  (resolved via model_aliases:)
#     $resolved.cli      # "claude"
#     $resolved.context  # 1000000
#     $resolved.flags    # "--dangerously-skip-permissions ..."
#
# Override: N07 can pass CEX_MODEL_OVERRIDE env var to force a specific model:
#     $env:CEX_MODEL_OVERRIDE = "claude-sonnet-4-6"
#     Then Resolve-NucleusModel returns that instead of YAML value.
#
# Why: boot scripts generated by cex_boot_gen.py used to hardcode the model.
# If nucleus_models.yaml changed, boot scripts were stale. This resolver
# reads YAML at boot time so the config is always authoritative.
#
# ASCII-safe (no emoji per .claude/rules/ascii-code-rule.md)
#
# Dynamic model alias resolution (plan: opus_latest_dynamic). This PS resolver
# mirrors _tools/cex_model_resolver.py exactly: the shorthand ("opus") expands
# by reading the model_aliases: block from nucleus_models.yaml, overlaid by a
# fresh (<24h) .cex/cache/model_discovery.json, with CEX_OPUS_TIER as an opus
# pin. The ONE baked-in baseline below is the DP4 last-resort net so boot never
# hard-fails. (The PRIMARY PS path is still cex_boot_pipeline.py, which is also
# alias-aware; this regex parser is the no-Python fallback.)

# The ONE place a default Opus version lives in this PS resolver (DP4 net).
$script:BaselineOpus = "claude-opus-4-8"

# ---------------------------------------------------------------------------
# FABLE_SELF_HEAL: availability-aware fable -> opus substitution
# ---------------------------------------------------------------------------
# Mirrors _tools/cex_model_resolver.py byte-for-byte in DECISION. claude-fable-5
# can be server-blocked per-account by Anthropic; the block lives in the user's
# ~/.claude.json under cachedGrowthBookFeatures.tengu-model-error-overrides as a
# `claude-fable-5` key. A blocked model crashes the CLI at launch, so we resolve
# opus WHILE blocked and snap back to fable the instant Anthropic clears the key.
$script:FableModelId = "claude-fable-5"
$script:FableNoteEmitted = $false

function Test-CexTruthy {
    # True iff the value is a truthy token (1/true/yes/on). Mirrors _env_truthy.
    param([string]$Value)
    if (-not $Value) { return $false }
    return @('1', 'true', 'yes', 'on') -contains $Value.Trim().ToLower()
}

function Get-CexFableGatePath {
    # CEX_FABLE_GATE override (test seam + escape hatch) else %USERPROFILE%\.claude.json.
    if ($env:CEX_FABLE_GATE) { return $env:CEX_FABLE_GATE }
    return (Join-Path $env:USERPROFILE ".claude.json")
}

function Test-CexFableBlocked {
    # Mirror of cex_model_resolver._fable_blocked. Returns $true iff claude-fable-5
    # is server-blocked (a claude-fable-5 key under
    # cachedGrowthBookFeatures.tengu-model-error-overrides). FAIL-SAFE: a missing /
    # unreadable / unparseable gate file returns $true (treat as BLOCKED -> opus),
    # because a blocked fable crashes boot. No network call.
    $gate = Get-CexFableGatePath
    if (-not (Test-Path $gate)) { return $true }          # missing -> FAIL-SAFE blocked
    try {
        $data = Get-Content $gate -Raw -Encoding UTF8 | ConvertFrom-Json
    } catch {
        return $true                                       # unparseable -> FAIL-SAFE blocked
    }
    try {
        $gb = $data.cachedGrowthBookFeatures
        if (-not $gb) { return $false }                    # readable, no block group -> AVAILABLE
        $ov = $gb.'tengu-model-error-overrides'
        if (-not $ov) { return $false }                    # no override block -> AVAILABLE
        return ($ov.PSObject.Properties.Name -contains $script:FableModelId)
    } catch {
        return $true                                       # structural surprise -> FAIL-SAFE
    }
}

function Write-CexFableNoteOnce {
    # One-shot console note (host stream -- does NOT pollute function return values).
    if ($script:FableNoteEmitted) { return }
    $script:FableNoteEmitted = $true
    Write-Host "  [i] claude-fable-5 server-blocked -> resolving opus (set CEX_FABLE_FORCE=1 to force fable)." -ForegroundColor DarkGray
}

function Resolve-CexFableHeal {
    # Substitute opus for claude-fable-5 WHILE blocked. Triggers ONLY for the fable
    # target (opus/sonnet/haiku pass through unchanged). CEX_FABLE_FORCE bypasses.
    # The opus substitution reuses Resolve-CexShorthand so CEX_OPUS_TIER + discovery
    # cache precedence is preserved. Mirrors cex_model_resolver._heal_fable.
    param([string]$Resolved, [string]$CexRoot)
    if ($Resolved -ne $script:FableModelId) { return $Resolved }
    if (Test-CexTruthy $env:CEX_FABLE_FORCE) { return $Resolved }
    if (Test-CexFableBlocked) {
        Write-CexFableNoteOnce
        return (Resolve-CexShorthand -Name "opus" -CexRoot $CexRoot)
    }
    return $Resolved
}

function Get-CexModelAliases {
    # Read the model_aliases: block from nucleus_models.yaml into a hashtable
    # {alias_key = model_id}. Returns @{} on any failure (caller degrades to
    # the baked-in fallback map). No network call.
    param([string]$CexRoot)
    $aliases = @{}
    try {
        $yamlPath = Join-Path $CexRoot ".cex\config\nucleus_models.yaml"
        if (-not (Test-Path $yamlPath)) { return $aliases }
        $content = Get-Content $yamlPath -Raw -Encoding UTF8
        # Capture the top-level model_aliases: block up to the next top-level key.
        if ($content -match "(?ms)^model_aliases:[ \t]*\r?\n(.*?)(?=^\S|\Z)") {
            foreach ($line in ($Matches[1] -split "\r?\n")) {
                # indented "  key: value"  (strip any inline # comment)
                if ($line -match "^[ \t]+([A-Za-z0-9_]+):[ \t]*([^\s#]+)") {
                    $aliases[$Matches[1]] = $Matches[2]
                }
            }
        }
    } catch { }
    return $aliases
}

function Get-CexDiscoveryCache {
    # DP1 READ side: .cex/cache/model_discovery.json if its _fetched is < 24h
    # old. Returns @{} on missing/stale/unparseable. Pure file read + timestamp
    # compare -- NO network call, never blocks boot.
    param([string]$CexRoot)
    $result = @{}
    try {
        $cachePath = Join-Path $CexRoot ".cex\cache\model_discovery.json"
        if (-not (Test-Path $cachePath)) { return $result }
        $data = Get-Content $cachePath -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($data._fetched) {
            $age = (Get-Date).ToUniversalTime() - ([datetime]$data._fetched).ToUniversalTime()
            if ($age.TotalHours -lt 24) {
                foreach ($p in $data.PSObject.Properties) {
                    if ($p.Name -notlike "_*" -and $p.Value) { $result[$p.Name] = [string]$p.Value }
                }
            }
        }
    } catch { }
    return $result
}

function Resolve-CexShorthand {
    # Expand a shorthand (opus/sonnet/haiku/gemini_pro/gemini_flash/gpt/gpt_mini)
    # to a full model id, or pass a literal through. Precedence (high->low):
    #   CEX_OPUS_TIER pin (opus family only) > discovery cache > YAML alias >
    #   baked-in fallback. Mirrors cex_model_resolver.resolve_shorthand.
    param([string]$Name, [string]$CexRoot)
    if (-not $Name) { return $script:BaselineOpus }
    $toAlias = @{
        "fable" = "fable_latest"; "opus" = "opus_latest"; "sonnet" = "sonnet_latest"; "haiku" = "haiku_latest";
        "gemini_pro" = "gemini_pro_latest"; "gemini_flash" = "gemini_flash_latest";
        "gpt" = "gpt_latest"; "gpt_mini" = "gpt_mini_latest"
    }
    # already a literal id -- but still self-heal a literal claude-fable-5
    if (-not $toAlias.ContainsKey($Name)) { return (Resolve-CexFableHeal -Resolved $Name -CexRoot $CexRoot) }
    $aliasKey = $toAlias[$Name]
    # CEX_OPUS_TIER pins the opus family to a literal version (rollback path).
    if ($aliasKey -eq "opus_latest" -and $env:CEX_OPUS_TIER) {
        if ($env:CEX_OPUS_TIER.ToLower() -ne "latest") { return $env:CEX_OPUS_TIER }
    }
    # Layer 1: baked-in fallback (opus anchored to the single baseline const).
    $fallback = @{
        "fable_latest" = "claude-fable-5"; "opus_latest" = $script:BaselineOpus; "sonnet_latest" = "claude-sonnet-4-6";
        "haiku_latest" = "claude-haiku-4-5-20251001"; "gemini_pro_latest" = "gemini-2.5-pro";
        "gemini_flash_latest" = "gemini-2.5-flash"; "gpt_latest" = "gpt-5.2"; "gpt_mini_latest" = "gpt-5-mini"
    }
    $resolved = $fallback[$aliasKey]
    # Layer 2: YAML model_aliases: block.
    $yamlAliases = Get-CexModelAliases -CexRoot $CexRoot
    if ($yamlAliases.ContainsKey($aliasKey)) { $resolved = $yamlAliases[$aliasKey] }
    # Layer 3: fresh discovery cache OVERRIDES the YAML alias (DP1).
    $cache = Get-CexDiscoveryCache -CexRoot $CexRoot
    if ($cache.ContainsKey($aliasKey)) { $resolved = $cache[$aliasKey] }
    if (-not $resolved) { $resolved = $script:BaselineOpus }
    # FABLE_SELF_HEAL: opus while claude-fable-5 is server-blocked, fable when clear.
    return (Resolve-CexFableHeal -Resolved $resolved -CexRoot $CexRoot)
}

# ---------------------------------------------------------------------------
# THIN_BOOT: REALIZE the per-nucleus boot cut (spec_nucleus_boot_a2a Phase A.5)
# ---------------------------------------------------------------------------
# Kills the ~10k/spawn N07-only-rules tax that N01-N06 carry today. Claude Code
# AUTO-LOADS CLAUDE.md + every .claude/rules/*.md, so appending an assembled prefix
# would ADD on top (the Phase-A trap). Phase A.5 instead REALIZES the cut natively:
# a flag-conditional `claudeMdExcludes` settings overlay that DE-AUTO-LOADS the rules
# a builder never needs (proven on disk via the spawn probe). Gated by CEX_THIN_BOOT
# (default OFF). OFF -> the caller passes the plain stub (byte-identical, zero
# regression). Assembler: _tools/cex_boot_context.py (--emit-exclude-settings).

# TBFIX -- KIND-AWARE thin boot (MISSION_BENCH: thin boot fails T3 orchestration). A
# builder PRODUCING an orchestration artifact keeps FULL boot. PS mirrors the EXPLICIT
# orchestration set (the founder-named "P12-ish" kinds); _tools/cex_boot_context.py is
# the AUTHORITATIVE resolver and unions this with the live kinds_meta P12 pillar, so a
# P12 kind outside this list is still caught when boot calls python to realize the cut
# (python returns mode=legacy -> the caller falls back to the full-boot stub). Mirror of
# cex_boot_context.ORCHESTRATION_KINDS_EXPLICIT.
$script:OrchestrationKinds = @(
    'workflow', 'pipeline_template', 'dag', 'saga', 'state_machine',
    'crew_template', 'handoff_protocol', 'process_manager', 'supervisor',
    'visual_workflow', 'workflow_node'
)

function Test-CexOrchestrationKind {
    # $true iff $Kind is orchestration-class (-> keep FULL boot). Empty/unknown -> $false
    # (no extra full boot; python's wider P12 union is the backstop when realizing the cut).
    # Mirrors cex_boot_context.is_orchestration_kind for the explicit set.
    param([string]$Kind)
    if (-not $Kind) { return $false }
    return $script:OrchestrationKinds -contains $Kind.Trim().ToLower()
}

function Get-CexHandoffKind {
    # Read the pending dispatch handoff's frontmatter `kind:` for $Nucleus -- the kind the
    # builder is about to PRODUCE -- so an orchestration-class build keeps FULL boot
    # (MISSION_BENCH T3). Scans only the leading YAML frontmatter (between the first two
    # '---' fences) so a `related:` list item or body prose never false-matches. Returns
    # "" on no handoff / no kind line -> the existing GRAD behavior (no extra thinning).
    # Never throws (boot must never break).
    param([string]$CexRoot, [string]$Nucleus)
    try {
        # Tenant-scoped handoff (R-279): 'runtime' is a per-tenant surface, so a
        # tenant session's pending-kind probe reads its OWN handoff, never the
        # central one -- same CEX_TENANT_ID-aware $handoffRel ternary as the
        # boot/n0X.ps1 family. LOAD-BEARING: this path decides thin-vs-full boot.
        $handoffRel = if ($env:CEX_TENANT_ID) { ".cex/tenants/$($env:CEX_TENANT_ID)/runtime/handoffs/${Nucleus}_task.md" } else { ".cex/runtime/handoffs/${Nucleus}_task.md" }
        $handoff = Join-Path $CexRoot $handoffRel
        if (-not (Test-Path $handoff)) { return "" }
        $lines = Get-Content $handoff -TotalCount 30 -EA SilentlyContinue
        $inFm = $false
        foreach ($line in $lines) {
            if ($line -match '^---\s*$') {
                if ($inFm) { break }      # closing fence -> stop (frontmatter ended)
                $inFm = $true; continue   # opening fence
            }
            if ($inFm -and $line -match '^kind:\s*(.+?)\s*$') {
                return $Matches[1].Trim().Trim('"').Trim("'").ToLower()
            }
        }
    } catch { }
    return ""
}

function Test-CexThinBoot {
    # A.5 gate: $true iff the resolved level is 'on'. nucleus-aware UNSET default (GRAD):
    # unset -> 'on' for builders n01-n06, 'off' for n07/unknown. Explicit 0/off -> 'off'
    # (the byte-identical rollback); =full -> $false here (the full path is taken first).
    # TBFIX: an orchestration-class $Kind downgrades the level to 'off' here too (full boot).
    # Delegates to Get-CexThinBootLevel so PS + Python share ONE default contract.
    param([string]$Nucleus = "", [string]$Kind = "")
    return ((Get-CexThinBootLevel -Nucleus $Nucleus -Kind $Kind) -eq "on")
}

function Resolve-CexThinBootSettings {
    # When CEX_THIN_BOOT is on, build a COMBINED settings file (the nucleus's base
    # stub -- permissions + the L2 constitution UserPromptSubmit hook -- MERGED with a
    # claudeMdExcludes array that de-auto-loads the N07-only rules) via
    # cex_boot_context.py and return its path for the caller to pass as a SINGLE
    # --settings. When off, n07 (owns its rules), OR ANY failure -> return $null so the
    # caller passes the plain $BaseSettings verbatim (byte-identical -- the FALLBACK).
    # The constitution is an --append-system-prompt and is never excluded. Never throws.
    # TBFIX: keep FULL boot for an orchestration-class build. $Kind (the pending build kind)
    # is read from the nucleus's handoff frontmatter when the caller doesn't pass one (boot
    # scripts don't) -- an orchestration kind returns $null here (the plain full-boot stub).
    param(
        [Parameter(Mandatory=$true)][string]$CexRoot,
        [Parameter(Mandatory=$true)][string]$Nucleus,
        [string]$BaseSettings = "",
        [string]$Kind = ""
    )
    # Cheap nucleus-only pre-check: explicit-off (rollback) / n07 short-circuits with NO
    # handoff read -> the OFF path stays byte-identical and I/O-free.
    if ((Get-CexThinBootLevel -Nucleus $Nucleus) -eq "off") { return $null }
    # Otherwise we'd thin -- unless this is an orchestration-class build. Resolve the kind
    # from the pending handoff when the caller didn't pass one.
    if (-not $Kind) { $Kind = Get-CexHandoffKind -CexRoot $CexRoot -Nucleus $Nucleus }
    if (-not (Test-CexThinBoot -Nucleus $Nucleus -Kind $Kind)) {
        if (Test-CexOrchestrationKind -Kind $Kind) {
            Write-Host ("  [i] orchestration build ({0}): keeping FULL boot (thin boot skipped)" -f $Kind) -ForegroundColor DarkGray
        }
        return $null
    }
    try {
        $cliArgs = @("$CexRoot\_tools\cex_boot_context.py", "--nucleus", $Nucleus,
                     "--emit-exclude-settings", "--json")
        if ($Kind) { $cliArgs += @("--kind", $Kind) }
        if ($BaseSettings) { $cliArgs += @("--stub", $BaseSettings) }
        $json = python @cliArgs 2>$null
        if ($LASTEXITCODE -ne 0 -or -not $json) { return $null }
        $r = $json | ConvertFrom-Json
        if ($r.mode -ne "thin" -or -not $r.settings_path) { return $null }
        Write-Host ("  [i] CEX_THIN_BOOT on: {0} de-auto-loads {1} rule(s), -{2} tok/spawn" -f `
            $Nucleus, $r.excluded_rules.Count, $r.excluded_tokens) -ForegroundColor DarkGray
        return $r.settings_path
    } catch {
        return $null
    }
}

# ---------------------------------------------------------------------------
# B1 FULL split (the 85% path) -- level CEX_THIN_BOOT=full, SHIPPED OFF
# ---------------------------------------------------------------------------
# The DEEPER cut: de-auto-load the ENTIRE auto-load (CLAUDE.md + every .claude/rules/*.md)
# for a builder and re-inject a curated, cacheable subset via --append-system-prompt --
# a SHARED CORE (constitution + thin root + universal spine, byte-identical across nuclei
# = one cache key) + the per-nucleus identity seed (CLAUDE.n0X.md). The orchestration
# rules are dropped (still on disk, read on demand). Gated on the 'full' level ONLY: the
# default + A.5's '=1' (on) level are UNCHANGED (byte-identical). n07 is out of scope.

function Get-CexThinBootLevel {
    # 3-state CEX_THIN_BOOT level: 'off' | 'on' (A.5) | 'full' (B1 split). Mirrors
    # cex_boot_context.thin_boot_level (ONE contract across PS + Python). Precedence:
    # explicit env token > nucleus-aware UNSET default -> then the TBFIX orchestration
    # downgrade (last). GRAD: when CEX_THIN_BOOT is UNSET (absent or empty), a builder
    # nucleus (n01-n06) defaults to 'on' (A.5 graduated to default-ON); n07 / no-nucleus
    # default to 'off' (N07 keeps the full rule-set). EXPLICIT 0/false/no/off forces 'off'
    # for every nucleus (the byte-identical rollback); an unrecognized non-empty token is
    # conservative 'off'. Legacy truthy tokens -> 'on'.
    # TBFIX: if $Kind is orchestration-class, a thinning level (on/full) is DOWNGRADED to
    # 'off' -- the builder keeps full boot for an orchestration build. Only ever downgrades
    # (off stays off); a non-orch / empty $Kind leaves the result byte-identical.
    param([string]$Nucleus = "", [string]$Kind = "")
    $v = ""
    if ($env:CEX_THIN_BOOT) { $v = $env:CEX_THIN_BOOT.Trim().ToLower() }
    $level = "off"
    if ($v -eq "full") { $level = "full" }
    elseif (@('1', 'true', 'yes', 'on') -contains $v) { $level = "on" }
    elseif (@('0', 'false', 'no', 'off') -contains $v) { $level = "off" }
    elseif ($v -eq "") {
        if (@('n01', 'n02', 'n03', 'n04', 'n05', 'n06') -contains $Nucleus.ToLower()) { $level = "on" }
        else { $level = "off" }
    }
    else { $level = "off" }
    if ($level -ne "off" -and (Test-CexOrchestrationKind -Kind $Kind)) { return "off" }
    return $level
}

function Resolve-CexFullBoot {
    # B1 full split. When the level is 'full' AND the nucleus is in scope (n01-n06),
    # build the shared core + combined full-exclude settings via cex_boot_context.py and
    # return a parsed object { append_paths = [...]; settings_path = "..." } for the boot
    # to use INSTEAD of the legacy appends. Off / on / n07 / ANY failure -> $null so the
    # caller falls back to the legacy (or A.5) path (byte-identical -- the FALLBACK).
    # The constitution rides FIRST in the shared core and is never excluded. Never throws.
    # TBFIX: an orchestration-class build keeps FULL (legacy) boot -- Get-CexThinBootLevel
    # -Kind downgrades 'full' -> 'off' so this returns $null and the caller falls back to
    # the A.5/legacy path (which also keeps full boot for the orchestration kind).
    param(
        [Parameter(Mandatory=$true)][string]$CexRoot,
        [Parameter(Mandatory=$true)][string]$Nucleus,
        [string]$BaseSettings = "",
        [string]$Kind = ""
    )
    if (-not $Kind) { $Kind = Get-CexHandoffKind -CexRoot $CexRoot -Nucleus $Nucleus }
    if ((Get-CexThinBootLevel -Nucleus $Nucleus -Kind $Kind) -ne "full") { return $null }
    try {
        $cliArgs = @("$CexRoot\_tools\cex_boot_context.py", "--nucleus", $Nucleus,
                     "--emit-full-split", "--full", "--json")
        if ($Kind) { $cliArgs += @("--kind", $Kind) }
        if ($BaseSettings) { $cliArgs += @("--stub", $BaseSettings) }
        $json = python @cliArgs 2>$null
        if ($LASTEXITCODE -ne 0 -or -not $json) { return $null }
        $r = $json | ConvertFrom-Json
        if ($r.mode -ne "full" -or -not $r.append_file) { return $null }
        Write-Host ("  [i] CEX_THIN_BOOT=full: {0} full split -- de-auto-loads {1} file(s) (-{2} tok gross/spawn), re-injects cached core + slice" -f `
            $Nucleus, $r.excluded_rules.Count, $r.excluded_tokens) -ForegroundColor DarkGray
        return $r
    } catch {
        return $null
    }
}

# ---------------------------------------------------------------------------
# LEVERAGE_APPEND_FILE_FIX -- single combined --append-system-prompt-file
# ---------------------------------------------------------------------------
# Make L1 boot-hydration actually inject. Three CLI facts, all proven on disk via
# the claude -p sentinel probe:
#   1. --append-system-prompt <path> appends the literal PATH STRING, not the file
#      content. Only --append-system-prompt-file injects a file's CONTENT.
#   2. BOTH forms are LAST-WINS: with N occurrences only the LAST reaches the system
#      prompt (the earlier ones are discarded, not concatenated).
#   3. The two forms are MUTUALLY EXCLUSIVE: passing both hard-errors
#      ("Cannot use both --append-system-prompt and --append-system-prompt-file").
# Net: the ENTIRE L1 set (agent_card + nucleus_kinds + constitution + the sin/role
# sysPrompt) must ride in ONE file passed as a single --append-system-prompt-file.
# This function builds that file; the boot passes its path. Composes with thin boot:
# off/=1(A.5) feed the base source files; =full feeds the cacheable core+tail (the
# constitution rides FIRST in the core -> no double constitution).

function Write-CexBootAppend {
    # Concatenate $Sources (skip-missing, exactly as the CLI silently skipped a missing
    # --append-system-prompt path) plus the inline $SysPrompt into ONE file under the
    # gitignored boot cache; return its path. Returns $null on ANY failure (no readable
    # source, write error) so the caller falls back to the legacy string appends
    # (boot-safe -- the constitution still arrives via the L2 hook + L4 gate). Writes
    # UTF-8 WITHOUT BOM: the CLI append-file reader is byte-oriented, so a BOM would
    # inject a stray U+FEFF at the top of the system prompt. Never throws.
    param(
        [Parameter(Mandatory=$true)][string]$CexRoot,
        [Parameter(Mandatory=$true)][string]$Nucleus,
        [Parameter(Mandatory=$true)][AllowEmptyCollection()][string[]]$Sources,
        [string]$SysPrompt = ""
    )
    try {
        $parts = @()
        foreach ($s in $Sources) {
            if ($s -and (Test-Path -LiteralPath $s)) {
                $parts += (Get-Content -Raw -Encoding UTF8 -LiteralPath $s)
            }
        }
        if ($SysPrompt) { $parts += $SysPrompt }
        if ($parts.Count -eq 0) { return $null }
        $body = ($parts -join "`n`n")
        $cacheDir = Join-Path $CexRoot ".cex/cache/boot"
        if (-not (Test-Path -LiteralPath $cacheDir)) {
            New-Item -ItemType Directory -Force -Path $cacheDir | Out-Null
        }
        $finalPath = Join-Path $cacheDir ("append_final_{0}.md" -f $Nucleus)
        $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
        [System.IO.File]::WriteAllText($finalPath, $body, $utf8NoBom)
        return $finalPath
    } catch {
        return $null
    }
}

function Resolve-NucleusModel {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Nucleus,
        [Parameter(Mandatory=$true)]
        [string]$CexRoot
    )

    # --- Orchestrator override (highest priority) ---
    # N07 sets CEX_MODEL_OVERRIDE via spawn_grid.ps1 to force a model
    # (e.g. grid-haiku, grid with -Model flag). Must be checked FIRST,
    # before boot pipeline or YAML, so the override always wins.
    if ($env:CEX_MODEL_OVERRIDE) {
        Write-Host "  [i] Model override active: $($env:CEX_MODEL_OVERRIDE)" -ForegroundColor Cyan
        $overrideModel = $env:CEX_MODEL_OVERRIDE
        $overrideCli = "claude"
        if ($overrideModel -match "^gemini") { $overrideCli = "gemini" }
        if ($overrideModel -match "^gpt")    { $overrideCli = "codex" }
        if ($overrideModel -match "^llama|^qwen|^gemma") { $overrideCli = "ollama" }
        return @{
            cli     = $overrideCli
            model   = $overrideModel
            context = 1000000
            flags   = "--dangerously-skip-permissions --permission-mode bypassPermissions"
            mcps    = ""
            settings = ""
            tier    = "full_8f"
        }
    }

    # --- Boot pipeline (primary) ---
    # Tries cex_boot_pipeline.py for full resolution chain (intent resolver,
    # router_v2, preflight cache, boot_log audit). On any failure, falls
    # through to the legacy YAML regex parser below. Boot must NEVER break.
    # v1.1.0: previously only n07 called the pipeline; n01-n06 bypassed it.
    if (-not $env:CEX_SKIP_BOOT_PIPELINE) {
        try {
            $pipelineJson = python "$CexRoot\_tools\cex_boot_pipeline.py" --nucleus $Nucleus --json 2>$null
            if ($LASTEXITCODE -eq 0 -and $pipelineJson) {
                $p = $pipelineJson | ConvertFrom-Json
                if ($p.model) {
                    return @{
                        cli      = if ($p.cli)      { $p.cli }      else { "claude" }
                        model    = $p.model
                        context  = if ($p.context)  { [int]$p.context } else { 1000000 }
                        flags    = if ($p.flags)    { $p.flags }    else { "--dangerously-skip-permissions --permission-mode bypassPermissions" }
                        mcps     = if ($p.mcps)     { $p.mcps }     else { "" }
                        settings = if ($p.settings) { $p.settings } else { "" }
                        tier     = if ($p.tier)     { $p.tier }     else { "full_8f" }
                    }
                }
            }
        } catch {
            # Pipeline failed (no python, missing deps, etc). Fall through.
        }
    }

    $yamlPath = Join-Path $CexRoot ".cex\config\nucleus_models.yaml"
    if (-not (Test-Path $yamlPath)) {
        Write-Host "  [WARN] nucleus_models.yaml not found at $yamlPath" -ForegroundColor Yellow
        Write-Host "  [WARN] Falling back to $script:BaselineOpus" -ForegroundColor Yellow
        return @{
            cli     = "claude"
            model   = $script:BaselineOpus
            context = 1000000
            flags   = "--dangerously-skip-permissions --permission-mode bypassPermissions"
            mcps    = ""
            settings = ""
            tier    = "full_8f"
        }
    }

    # Parse YAML with native PowerShell regex (no Python dependency).
    # The nucleus_models.yaml structure is flat enough for regex extraction.
    # Previous Python-based parser failed silently in spawned processes
    # where python was not in PATH (2026-04-25 grid failure).
    $yamlContent = Get-Content $yamlPath -Raw -Encoding UTF8

    # Find the nucleus block: starts with "^{nucleus}:" and ends at next "^[a-z]:" or EOF
    $pattern = "(?m)^${Nucleus}:\s*\r?\n((?:[ #].*\r?\n)*)"
    if ($yamlContent -notmatch $pattern) {
        Write-Host "  [WARN] Nucleus '$Nucleus' not found in YAML -- fallback to opus" -ForegroundColor Yellow
        return @{
            cli     = "claude"
            model   = $script:BaselineOpus
            context = 1000000
            flags   = "--dangerously-skip-permissions --permission-mode bypassPermissions"
            mcps    = ""
            settings = ""
            tier    = "full_8f"
        }
    }
    $block = $Matches[1]

    # Extract fields with simple regex (key: value or key: "value")
    function Get-YamlField($text, $field, $default) {
        if ($text -match "(?m)^\s+${field}:\s+`"([^`"]*)`"") { return $Matches[1] }
        if ($text -match "(?m)^\s+${field}:\s+`'([^`']*)`'") { return $Matches[1] }
        if ($text -match "(?m)^\s+${field}:\s+(\S+)") { return $Matches[1] }
        return $default
    }

    $result = @{
        cli      = Get-YamlField $block "cli" "claude"
        model    = Get-YamlField $block "model" "opus"
        context  = [int](Get-YamlField $block "context" "1000000")
        flags    = Get-YamlField $block "flags" ""
        mcps     = Get-YamlField $block "mcps" ""
        settings = Get-YamlField $block "settings" ""
        tier     = Get-YamlField $block "tier" "full_8f"
    }

    # Expand shorthand ("opus") to the full model id via the dynamic resolver:
    # reads model_aliases: from YAML, overlaid by a fresh discovery cache, with
    # CEX_OPUS_TIER as an opus pin. Single source of truth -- no hardcoded map.
    $result.model = Resolve-CexShorthand -Name $result.model -CexRoot $CexRoot

    Write-Host "  [i] Tier: $($result.tier)" -ForegroundColor DarkGray

    # Safety: if model is still empty after parsing, use the baseline default
    if (-not $result.model -or $result.model -eq "" -or $result.model -eq '""') {
        Write-Host "  [WARN] Empty model after parse -- fallback to baseline" -ForegroundColor Yellow
        $result.model = $script:BaselineOpus
    }
    if (-not $result.flags -or $result.flags -eq "" -or $result.flags -eq '""') {
        $result.flags = "--dangerously-skip-permissions --permission-mode bypassPermissions"
    }

    return $result
}

# ---------------------------------------------------------------------------
# R-111 fix -- dynamic fallback-model lookup for CLI-override boot variants
# ---------------------------------------------------------------------------
# boot/cex_gemini.ps1 and boot/n07_gemini.ps1 (N07's two Gemini-CLI boot variants)
# used to hardcode two DIFFERENT Gemini models ("gemini-2.5-flash-lite" vs
# "gemini-2.5-flash") -- neither read nucleus_models.yaml. This reads the
# fallback_chain: list for $Nucleus and returns the model for the first entry
# whose cli matches $Cli, so both scripts stay in lockstep with the YAML
# automatically. Regex-based (same philosophy as Get-YamlField above -- the
# fallback_chain entries are one-line YAML flow-mappings, e.g.
# "- {cli: gemini, model: gemini-2.5-flash-lite, flags: ..., tier: ...}").
# Degrade-never: returns $Default (never $null/throws) on ANY parse miss so a
# YAML edit/typo can't break a gemini-CLI boot.
function Resolve-NucleusFallbackModel {
    param(
        [Parameter(Mandatory=$true)][string]$Nucleus,
        [Parameter(Mandatory=$true)][string]$Cli,
        [Parameter(Mandatory=$true)][string]$CexRoot,
        [Parameter(Mandatory=$true)][string]$Default
    )
    try {
        $yamlPath = Join-Path $CexRoot ".cex\config\nucleus_models.yaml"
        if (-not (Test-Path $yamlPath)) { return $Default }
        $yamlContent = Get-Content $yamlPath -Raw -Encoding UTF8
        $pattern = "(?m)^${Nucleus}:\s*\r?\n((?:[ #].*\r?\n)*)"
        if ($yamlContent -notmatch $pattern) { return $Default }
        $block = $Matches[1]
        foreach ($line in ($block -split "\r?\n")) {
            if ($line -match "^\s*-\s*\{.*\bcli:\s*${Cli}\b.*\}\s*$") {
                if ($line -match "\bmodel:\s*([^,}\s]+)") { return $Matches[1] }
            }
        }
        return $Default
    } catch {
        return $Default
    }
}
